services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 718
      MARIADB_DATABASE: study-platform
      TZ: Asia/Seoul
    volumes:
      - db:/var/lib/mysql:Z

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 718
    ports:
      - "8081:80"

volumes:
  db:
